swagger: '2.0'
info:
  version: "1.0.1"
  title: Searchable Encrypted Database
  description: |
    The API for accessing a searchable encrpyted database/ This is part of a project for the Secure Data Management course.

schemes:
  - https
produces:
  - application/json
paths:
  /clients:
    get:
      description: |
        Retrieves an array of all 'ApiClient' entities.
        Only permitted by the consultant
      parameters:
        - name: x-key
          in: header
          description: The encryption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/ApiClient"
        400:
          description: Something went wrong
    post:
      description: |
        Creates a new 'ApiClient' enitity
      parameters:
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
        - name: client
          in: body
          required: true
          schema:
            $ref: "#/definitions/ApiClient"
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong
  /clients/{clientId}:
    get:
      description: |
        Retrieves a  'ApiClient' entity.
        Only permitted by the consultant or the client itself
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/ApiClient"
        400:
          description: Something went wrong
    put:
      description: |
        Updates a  'ApiClient' entity.
        Only permitted by the consultant or the client itself
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
        - name: client
          in: body
          required: true
          schema:
            $ref: "#/definitions/ApiClient"
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong
    delete:
      description: |
        Deletes a  'ApiClient' entity.
        Only permitted by the consultant or the client itself
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong
  /clients/{clientId}/ApiRecords:
    get:
      description: |
        Retrieves an array of all 'ApiRecord' entities owned by the client indicated with the clientId.
        Only permitted by the consultant
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
        - name: query
          in: body
          required: true
          description: The query to filter the ApiRecords with
          schema:
            type: array
            items:
              $ref: "#/definitions/Query"
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/ApiRecord"
        400:
          description: Something went wrong
    post:
      description: |
        Creates a new 'ApiRecord' enitity for thr thw owning client
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
        - name: client
          in: body
          required: true
          schema:
            $ref: "#/definitions/ApiRecord"
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong
  /clients/{clientId}/ApiRecords/{ApiRecordId}:
    put:
      description: |
        Updates a  'ApiRecord' entity owned by the client.
        Only permitted by the consultant or the client itself
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: ApiRecordId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
        - name: client
          in: body
          required: true
          schema:
            $ref: "#/definitions/ApiRecord"
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong
    delete:
      description: |
        Deletes a  'ApiRecord' entity owned by the client.
        Only permitted by the consultant or the client itself
      parameters:
        - name: clientId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: ApiRecordId
          in: path
          type: integer
          required: true
          description: The ID of the client
        - name: x-key
          in: header
          description: The encruption key
          required: true
          type: string
        - name: x-key-type
          in: header
          description: The encruption key type
          required: true
          type: string
      responses:
        200:
          description: Successful response
        400:
          description: Something went wrong

definitions:
  Query:
    type: object
    required:
      - column
      - value
      - operator
    properties:
      column:
        type: string
        description: The clumn you want to filter on
      value:
        type: string
        description: The value you want to compare the entry against, text for key and numeric for value
      operator:
        type: string
        description: The operation to use for comparison
  ApiClient:
    type: object
    required:
      - fname
      - lname
      - email
    properties:
      id:
        type: integer
        description: The id of the client
      fname:
        type: string
        description: The first name of the client
      lname:
        type: string
        description: The last name of the client
      email:
        type: string
        description: The email of the client
      createdAt:
        type: string
        description: The creation date
      updatedAt:
        type: string
        description: The update date
  ApiRecord:
    type: object
    required:
      - name
      - value
    properties:
      id:
        type: integer
        description: The id of the client
      name:
        type: string
        description: The name of the ApiRecord
      value:
        type: string
        description: The value of the ApiRecord
      createdAt:
        type: string
        description: The creation date
      updatedAt:
        type: string
        description: The update date
      client_id:
        type: integer
        description: The id of the owning client